### ISSUE TITLE
No Way to get rankings from team or event.

### ISSUE THREAD

**Issue by Techno11** [wdavies973/TBA-API-V3#6]
There is no way to get rankings from team or event.

**Comment by Techno11** [comment]
The models exist, but are not gettable, settable, and are not in the parser

**Comment by Techno11** [comment]
Working on a fix now

**Comment by widavies** [comment]
Let me know if you'd like help with the fix, otherwise, I'll let you take care of it.

**Comment by Techno11** [comment]
I believe it is fixed in PR #7 for the most part.  There may be other routes that aren't added, but the parsers exist.

**Comment by widavies** [comment]
Alright, let me know if you need anything else.

**Comment by widavies** [comment]
Am I good to close this issue?
