### ISSUE TITLE
Match.getScoreBreakdown() return null

### ISSUE THREAD

**Issue by owen1050** [wdavies973/TBA-API-V3#8]
getScoreBreakdown has been returning null for every match I've tried. At first, I thought it was TBA API because it does say null is a possibility, but if you test "getMatch" on their API v3 page it correctly returns all the information. 

It very easily could be an error on my part. 

Thank you for making this! It is very very helpful and I wish 973 luck in elims tomorrow.

**Comment by widavies** [comment]
I'm so sorry! For some reason, I didn't see this issue on GitHub. I fixed it with the latest release, you can download it from the releases section. To use the new functionality:
```java
Match m = tba.getMatch("matchKey");
System.out.println(m.getRedScoreBreakdown().getValues().get("value-key"));
```
Replace the value key with the value you'd like to get, like ```totalPoints``` for instance.

And switch to ```m.getBlueScoreBreakdown()``` for the blue team score breakdown.
